import { useEffect, useRef, useState } from 'react';
import { api, type Conversation } from './api';

type MediaKind = 'audio' | 'video';
type WireSignal = { type: 'call.signal'; signalType: 'call.offer' | 'call.answer' | 'call.ice' | 'call.reject' | 'call.end'; callId: string; conversationId: string; fromUserId: string; media?: MediaKind; sdp?: RTCSessionDescriptionInit; candidate?: RTCIceCandidateInit };
type CallState = { phase: 'idle' | 'ringing' | 'connecting' | 'active'; callId?: string; conversation?: Conversation; kind?: MediaKind; incoming?: boolean; muted?: boolean; cameraOff?: boolean; error?: string };

export function useWebRtcCalls(conversations: Conversation[], selected: Conversation | null, select: (conversation: Conversation) => void) {
  const [state, setState] = useState<CallState>({ phase: 'idle' }); const stateRef = useRef(state); stateRef.current = state; const socket = useRef<WebSocket | null>(null); const peer = useRef<RTCPeerConnection | null>(null); const localStream = useRef<MediaStream | null>(null); const remoteStream = useRef<MediaStream | null>(null); const pendingOffer = useRef<WireSignal | null>(null); const pendingCandidates = useRef<RTCIceCandidateInit[]>([]); const localVideo = useRef<HTMLVideoElement | null>(null); const remoteVideo = useRef<HTMLVideoElement | null>(null); const conversationsRef = useRef(conversations); conversationsRef.current = conversations;

  const send = (payload: object) => { if (socket.current?.readyState === WebSocket.OPEN) socket.current.send(JSON.stringify(payload)); };
  const release = () => { peer.current?.close(); peer.current = null; for (const track of localStream.current?.getTracks() ?? []) track.stop(); localStream.current = null; remoteStream.current = null; pendingOffer.current = null; pendingCandidates.current = []; if (localVideo.current) localVideo.current.srcObject = null; if (remoteVideo.current) remoteVideo.current.srcObject = null; };
  const finish = (notify = true) => { const current = stateRef.current; if (notify && current.callId && current.conversation) send({ type: 'call.end', callId: current.callId, conversationId: current.conversation.id, targetUserId: current.conversation.peer.id }); release(); setState({ phase: 'idle' }); };
  const createPeer = (callId: string, conversation: Conversation, kind: MediaKind, stream: MediaStream, iceServers: RTCIceServer[]) => { const connection = new RTCPeerConnection({ iceServers }); peer.current = connection; localStream.current = stream; for (const track of stream.getTracks()) connection.addTrack(track, stream); connection.onicecandidate = event => { if (event.candidate) send({ type: 'call.ice', callId, conversationId: conversation.id, targetUserId: conversation.peer.id, candidate: event.candidate.toJSON() }); }; connection.ontrack = event => { remoteStream.current = event.streams[0] ?? new MediaStream([event.track]); if (remoteVideo.current) remoteVideo.current.srcObject = remoteStream.current; setState(current => ({ ...current, phase: 'active' })); }; connection.onconnectionstatechange = () => { if (['failed', 'closed', 'disconnected'].includes(connection.connectionState)) finish(false); }; if (localVideo.current) localVideo.current.srcObject = stream; return connection; };
  const addQueuedCandidates = async () => { if (!peer.current?.remoteDescription) return; for (const candidate of pendingCandidates.current.splice(0)) await peer.current.addIceCandidate(candidate).catch(() => {}); };

  useEffect(() => { let stopped = false; let retry = 0; const connect = () => { const channel = new WebSocket(api.realtimeUrl()); socket.current = channel; channel.onmessage = event => { let incoming: WireSignal; try { incoming = JSON.parse(String(event.data)) as WireSignal; } catch { return; } if (incoming.type !== 'call.signal') return; const conversation = conversationsRef.current.find(item => item.id === incoming.conversationId && item.peer.id === incoming.fromUserId); if (!conversation) return; if (incoming.signalType === 'call.offer' && incoming.sdp && incoming.media) { pendingOffer.current = incoming; select(conversation); setState({ phase: 'ringing', callId: incoming.callId, conversation, kind: incoming.media, incoming: true }); return; } if (!peer.current || stateRef.current.callId !== incoming.callId) return; if (incoming.signalType === 'call.answer' && incoming.sdp) void peer.current.setRemoteDescription(incoming.sdp).then(addQueuedCandidates); else if (incoming.signalType === 'call.ice' && incoming.candidate) { if (peer.current.remoteDescription) void peer.current.addIceCandidate(incoming.candidate).catch(() => {}); else pendingCandidates.current.push(incoming.candidate); } else if (incoming.signalType === 'call.reject' || incoming.signalType === 'call.end') finish(false); }; channel.onclose = () => { if (!stopped) window.setTimeout(connect, Math.min(1000 * 2 ** retry++, 15_000)); }; }; connect(); return () => { stopped = true; socket.current?.close(); release(); }; }, []);

  const start = async (kind: MediaKind) => { if (!selected || state.phase !== 'idle') return; try { const [{ iceServers }, stream] = await Promise.all([api.iceServers(), navigator.mediaDevices.getUserMedia({ audio: true, video: kind === 'video' })]); const callId = crypto.randomUUID(); const connection = createPeer(callId, selected, kind, stream, iceServers); setState({ phase: 'connecting', callId, conversation: selected, kind, incoming: false }); const offer = await connection.createOffer(); await connection.setLocalDescription(offer); send({ type: 'call.offer', callId, conversationId: selected.id, targetUserId: selected.peer.id, media: kind, sdp: offer }); } catch { release(); setState({ phase: 'idle', error: 'Não foi possível acessar câmera ou microfone.' }); } };
  const accept = async () => { const offer = pendingOffer.current; if (!offer?.conversationId || !offer.sdp || !state.conversation || !state.kind || !state.callId) return; try { const [{ iceServers }, stream] = await Promise.all([api.iceServers(), navigator.mediaDevices.getUserMedia({ audio: true, video: state.kind === 'video' })]); const connection = createPeer(state.callId, state.conversation, state.kind, stream, iceServers); await connection.setRemoteDescription(offer.sdp); await addQueuedCandidates(); const answer = await connection.createAnswer(); await connection.setLocalDescription(answer); send({ type: 'call.answer', callId: state.callId, conversationId: state.conversation.id, targetUserId: state.conversation.peer.id, sdp: answer }); setState(current => ({ ...current, phase: 'connecting', incoming: false })); } catch { finish(false); setState({ phase: 'idle', error: 'Permissão de mídia negada.' }); } };
  const reject = () => { if (state.callId && state.conversation) send({ type: 'call.reject', callId: state.callId, conversationId: state.conversation.id, targetUserId: state.conversation.peer.id }); finish(false); };
  const toggleMute = () => { const next = !state.muted; for (const track of localStream.current?.getAudioTracks() ?? []) track.enabled = !next; setState(current => ({ ...current, muted: next })); };
  const toggleCamera = () => { const next = !state.cameraOff; for (const track of localStream.current?.getVideoTracks() ?? []) track.enabled = !next; setState(current => ({ ...current, cameraOff: next })); };
  useEffect(() => { if (localVideo.current && localStream.current) localVideo.current.srcObject = localStream.current; if (remoteVideo.current && remoteStream.current) remoteVideo.current.srcObject = remoteStream.current; });
  return { state, localVideo, remoteVideo, start, accept, reject, finish, toggleMute, toggleCamera };
}

export function CallOverlay({ call }: { call: ReturnType<typeof useWebRtcCalls> }) {
  const { state } = call; if (state.phase === 'idle') return state.error ? <div className="call-error" role="alert">{state.error}</div> : null;
  if (state.phase === 'ringing') return <div className="call-overlay"><section className="incoming-call"><span>{state.kind === 'video' ? 'Vídeo' : 'Áudio'}</span><h2>{state.conversation?.peer.displayName} está ligando</h2><div><button className="reject" onClick={call.reject}>Recusar</button><button className="accept" onClick={call.accept}>Atender</button></div></section></div>;
  return <div className="call-overlay"><section className="active-call"><video ref={call.remoteVideo} autoPlay playsInline/><video className="local-video" ref={call.localVideo} autoPlay muted playsInline/><div className="call-caption"><strong>{state.conversation?.peer.displayName}</strong><span>{state.phase === 'active' ? 'Chamada protegida por WebRTC' : 'Conectando…'}</span></div><div className="call-controls"><button onClick={call.toggleMute}>{state.muted ? 'Ativar microfone' : 'Silenciar'}</button>{state.kind === 'video' && <button onClick={call.toggleCamera}>{state.cameraOff ? 'Ativar câmera' : 'Desativar câmera'}</button>}<button className="reject" onClick={() => call.finish(true)}>Encerrar</button></div></section></div>;
}
