import { StrictMode, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import type { DefaultSignalProtocolClient } from '@open-e2ee/signal-protocol-sdk';
import { api, type Conversation, type User } from './api';
import { createPrivyE2EE } from './e2ee';
import './styles.css';
import './phase2.css';
import './phase3.css';

function Icon({ children, size = 20 }: { children: ReactNode; size?: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{children}</svg>; }
const icons = {
  shield: <Icon><path d="M12 3 20 6v5c0 5-3.4 8.6-8 10-4.6-1.4-8-5-8-10V6l8-3Z"/><path d="m9 12 2 2 4-5"/></Icon>,
  lock: <Icon><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v2"/></Icon>,
  message: <Icon><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z"/></Icon>,
  call: <Icon><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.8a2 2 0 0 1-.4 2.1L8.1 9.9a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.4c.9.3 1.8.6 2.8.7a2 2 0 0 1 1.7 2Z"/></Icon>,
  device: <Icon><rect x="4" y="2" width="16" height="20" rx="3"/><path d="M9 18h6"/></Icon>,
  search: <Icon><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></Icon>,
  logout: <Icon><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9"/></Icon>,
  plus: <Icon><path d="M12 5v14M5 12h14"/></Icon>,
  close: <Icon><path d="m6 6 12 12M18 6 6 18"/></Icon>,
};
function Logo() { return <div className="brand"><span className="brand-mark">{icons.lock}</span><span>Privy</span></div>; }

function Auth({ onUser }: { onUser: (user: User) => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget); try { const username = String(data.get('username')); const password = String(data.get('password')); const result = mode === 'login' ? await api.login({ username, password }) : await api.register({ username, password, displayName: String(data.get('displayName')) }); onUser(result.user); } catch { setError('Não foi possível autenticar. Confira os dados e tente novamente.'); } finally { setBusy(false); } }
  return <main className="auth-page">
    <section className="auth-story"><Logo/><div className="story-copy"><span className="eyebrow"><i/> Privacidade por arquitetura</span><h1>Suas conversas.<br/><em>Somente suas.</em></h1><p>Comunicação privada projetada para manter o conteúdo longe de quem não deveria vê-lo — inclusive nós.</p></div><div className="trust-row"><div><span>{icons.shield}</span><p><strong>Proteção estrutural</strong><small>Dados privados permanecem no cliente</small></p></div><div><span>{icons.lock}</span><p><strong>Sem chave mestra</strong><small>O servidor não lê suas conversas</small></p></div></div><p className="story-foot">Privy · Comunicação privada, sem atalhos.</p></section>
    <section className="auth-panel"><div className="mobile-logo"><Logo/></div><div className="auth-card"><header><span className="form-icon">{icons.lock}</span><h2>{mode === 'login' ? 'Bem-vindo de volta' : 'Crie sua conta'}</h2><p>{mode === 'login' ? 'Acesse seu espaço de comunicação privada.' : 'Comece com uma identidade simples e segura.'}</p></header><div className="auth-tabs" role="tablist"><button type="button" role="tab" aria-selected={mode === 'login'} onClick={() => { setMode('login'); setError(''); }}>Entrar</button><button type="button" role="tab" aria-selected={mode === 'register'} onClick={() => { setMode('register'); setError(''); }}>Criar conta</button></div><form onSubmit={submit}>{mode === 'register' && <label><span>Nome exibido</span><input name="displayName" required maxLength={80} autoComplete="name" placeholder="Como quer ser chamado?"/></label>}<label><span>Nome de usuário</span><input name="username" required minLength={3} maxLength={32} autoComplete="username" placeholder="seu.usuario"/></label><label><span>Senha</span><input name="password" type="password" required minLength={12} maxLength={256} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} placeholder="Mínimo de 12 caracteres"/></label><div className="security-note">{icons.shield}<span>Sua senha autentica a conta, mas nunca é usada como chave de mensagem.</span></div>{error && <p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}><span>{busy ? 'Autenticando…' : mode === 'login' ? 'Entrar na minha conta' : 'Criar conta privada'}</span><b>→</b></button></form><footer>Ao continuar, você concorda com os termos e a política de privacidade.</footer></div></section>
  </main>;
}

function Home({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [conversations, setConversations] = useState<Conversation[]>([]); const [selected, setSelected] = useState<Conversation | null>(null); const [composerOpen, setComposerOpen] = useState(false); const [query, setQuery] = useState(''); const [results, setResults] = useState<User[]>([]); const [realtime, setRealtime] = useState(false);
  const [cryptoState, setCryptoState] = useState<'initializing' | 'ready' | 'error'>('initializing'); const [messages, setMessages] = useState<Array<{ id: string; peerId: string; body: string; mine: boolean; timestamp: number }>>([]); const [draft, setDraft] = useState(''); const [sending, setSending] = useState(false); const cryptoClient = useRef<DefaultSignalProtocolClient | null>(null);
  useEffect(() => { api.conversations().then(result => setConversations(result.conversations)).catch(() => {}); }, []);
  useEffect(() => { if (query.trim().length < 2) { setResults([]); return; } const timer = window.setTimeout(() => api.searchUsers(query.trim()).then(result => setResults(result.users)).catch(() => setResults([])), 250); return () => window.clearTimeout(timer); }, [query]);
  useEffect(() => { let socket: WebSocket | undefined; let timer = 0; let stopped = false; let delay = 1_000; const connect = () => { socket = new WebSocket(api.realtimeUrl()); socket.onopen = () => { delay = 1_000; setRealtime(true); }; socket.onclose = () => { setRealtime(false); if (!stopped) { timer = window.setTimeout(connect, delay); delay = Math.min(delay * 2, 30_000); } }; }; connect(); return () => { stopped = true; window.clearTimeout(timer); socket?.close(); }; }, []);
  useEffect(() => { let cancelled = false; let client: DefaultSignalProtocolClient | null = null; void createPrivyE2EE(user.id, message => { if (!cancelled) setMessages(current => current.some(item => item.id === message.messageId) ? current : [...current, { id: message.messageId, peerId: message.senderId, body: message.content, mine: false, timestamp: message.timestamp }]); }).then(value => { if (cancelled) return value.stopRelaySubscription(); client = value; cryptoClient.current = value; setCryptoState('ready'); }).catch(() => { if (!cancelled) setCryptoState('error'); }); return () => { cancelled = true; client?.stopRelaySubscription(); cryptoClient.current = null; }; }, [user.id]);
  async function startConversation(peer: User) { const result = await api.createConversation(peer.id); setConversations(current => [result.conversation, ...current.filter(item => item.id !== result.conversation.id)]); setSelected(result.conversation); setComposerOpen(false); setQuery(''); setResults([]); }
  async function sendMessage(event: FormEvent) { event.preventDefault(); const body = draft.trim(); if (!body || !selected || !cryptoClient.current || sending) return; setSending(true); try { await cryptoClient.current.send(selected.peer.id, body); setMessages(current => [...current, { id: crypto.randomUUID(), peerId: selected.peer.id, body, mine: true, timestamp: Date.now() }]); setDraft(''); } catch { setCryptoState('error'); } finally { setSending(false); } }
  const visibleMessages = selected ? messages.filter(message => message.peerId === selected.peer.id) : [];
  return <main className="app-shell">
    <aside className="sidebar"><Logo/><nav aria-label="Navegação principal"><p>Principal</p><button className="selected">{icons.message}<span>Conversas</span><b>{conversations.length}</b></button><button disabled>{icons.call}<span>Chamadas</span><small>Em breve</small></button><p>Segurança</p><button disabled>{icons.device}<span>Dispositivos</span><small>Fase 3</small></button></nav><div className="security-card"><span>{icons.shield}</span><div><strong>{realtime ? 'Tempo real conectado' : 'Reconectando…'}</strong><small>Sessão autenticada e isolada</small></div></div><div className="identity"><div className="avatar">{user.displayName[0]?.toUpperCase()}</div><div><strong>{user.displayName}</strong><small>@{user.username}</small></div><button aria-label="Sair" title="Sair" onClick={onLogout}>{icons.logout}</button></div></aside>
    <section className="conversation-list"><header><div><h1>Conversas</h1><p>{conversations.length} {conversations.length === 1 ? 'conversa' : 'conversas'}</p></div><button onClick={() => setComposerOpen(true)} aria-label="Nova conversa" title="Nova conversa">{icons.plus}</button></header><div className="conversation-search">{icons.search}<span>Buscar conversas</span></div><div className="conversation-items">{conversations.length === 0 ? <div className="list-empty"><span>{icons.message}</span><strong>Nenhuma conversa</strong><small>Encontre alguém para começar.</small></div> : conversations.map(conversation => <button key={conversation.id} className={selected?.id === conversation.id ? 'active' : ''} onClick={() => setSelected(conversation)}><span className="avatar peer">{conversation.peer.displayName[0]?.toUpperCase()}</span><span><strong>{conversation.peer.displayName}</strong><small>@{conversation.peer.username}</small></span><time>{new Date(conversation.createdAt).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' })}</time></button>)}</div></section>
    <section className="workspace">{selected ? <><header className="chat-header"><span className="avatar peer">{selected.peer.displayName[0]?.toUpperCase()}</span><div><h2>{selected.peer.displayName}</h2><p>@{selected.peer.username} · {cryptoState === 'ready' ? 'canal E2EE ativo' : cryptoState === 'error' ? 'falha criptográfica' : 'preparando chaves…'}</p></div><span className={`transport-state ${cryptoState}`}>{icons.shield} {cryptoState === 'ready' ? 'PQXDH + Double Ratchet' : 'Inicializando'}</span></header><div className="message-pane">{visibleMessages.length === 0 ? <div className="secure-intro"><span>{icons.lock}</span><strong>Conversa protegida de ponta a ponta</strong><p>As mensagens são cifradas neste navegador antes de chegar ao servidor.</p></div> : visibleMessages.map(message => <article key={message.id} className={message.mine ? 'message mine' : 'message'}><p>{message.body}</p><time>{new Date(message.timestamp).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })} {message.mine && '· cifrada'}</time></article>)}</div><form className="message-composer" onSubmit={sendMessage}><input value={draft} onChange={event => setDraft(event.target.value)} maxLength={10_000} disabled={cryptoState !== 'ready'} placeholder={cryptoState === 'ready' ? 'Escreva uma mensagem privada…' : 'Preparando criptografia…'}/><button disabled={!draft.trim() || cryptoState !== 'ready' || sending} aria-label="Enviar">{sending ? '…' : '↑'}</button></form></> : <div className="empty-state"><div className="empty-visual"><span>{icons.message}</span><i>{icons.lock}</i></div><span className="phase-label">Fase 3 · Criptografia ponta a ponta</span><h2>Escolha ou inicie uma conversa.</h2><p>Identidades, prekeys e estados do Double Ratchet vivem no navegador. O servidor recebe somente material público e ciphertext.</p><button className="secondary-action" onClick={() => setComposerOpen(true)}>{icons.plus} Nova conversa</button><div className="progress-card"><div className="progress-head"><span>Progresso da plataforma</span><strong>Fase 3 de 5</strong></div><div className="progress-track phase-three"><i/></div><div className="progress-steps"><span className="done">Fundação</span><span className="done">Transporte</span><span className="done">E2EE</span><span>Chamadas</span><span>Hardening</span></div></div></div>}<footer className="workspace-foot">{icons.shield}<span>Privacidade por design</span><i/><span>Nenhum conteúdo privado armazenado em texto puro</span></footer></section>
    {composerOpen && <div className="modal-backdrop" role="presentation" onMouseDown={() => setComposerOpen(false)}><section className="new-chat-modal" role="dialog" aria-modal="true" aria-labelledby="new-chat-title" onMouseDown={event => event.stopPropagation()}><header><div><h2 id="new-chat-title">Nova conversa</h2><p>Busque pelo nome ou usuário.</p></div><button onClick={() => setComposerOpen(false)} aria-label="Fechar">{icons.close}</button></header><label className="user-search">{icons.search}<input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Digite pelo menos 2 caracteres"/></label><div className="user-results">{query.length < 2 ? <p>Os resultados aparecerão aqui.</p> : results.length === 0 ? <p>Nenhum usuário encontrado.</p> : results.map(peer => <button key={peer.id} onClick={() => startConversation(peer)}><span className="avatar peer">{peer.displayName[0]?.toUpperCase()}</span><span><strong>{peer.displayName}</strong><small>@{peer.username}</small></span><b>Conversar →</b></button>)}</div></section></div>}
  </main>;
}

function App() { const [user, setUser] = useState<User | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { api.me().then(result => setUser(result.user)).catch(() => {}).finally(() => setLoading(false)); }, []); if (loading) return <div className="loading"><Logo/><span/></div>; return user ? <Home user={user} onLogout={() => api.logout().finally(() => setUser(null))}/> : <Auth onUser={setUser}/>; }
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
