import pg from 'pg';

export type PublicUser = { id: string; username: string; displayName: string; createdAt: string; avatarUpdatedAt: string | null };
export type StoredUser = PublicUser & { passwordHash: string };
export type Conversation = { id: string; createdAt: string; peer: PublicUser };
export type EncryptedMessage = { id: string; conversationId: string; senderDeviceId: string; recipientDeviceId: string; protocolVersion: number; envelope: string; clientMessageId: string; createdAt: string };
export type NewEnvelope = Omit<EncryptedMessage, 'id' | 'createdAt'>;
export type IdentityType = 'aci' | 'pni';
export type PublicIdentity = { version: 1; x25519PublicKey: string; ed25519PublicKey: string };
export type ProtocolDevice = { deviceId: number; encryptedDeviceName?: string; deviceType: 'web'; registered: boolean; linked: boolean; enabled: boolean; createdAt: number };
export type PreKeyUpload = { type: 'ecPreKey' | 'ecSignedPreKey' | 'kemOneTimePreKey' | 'kemLastResortPreKey'; keyId: number; publicKey: string; signature?: string | undefined };
export type RelayEnvelope = { id?: string | undefined; targetUserId: string; targetDeviceId: number; senderUserId: string; senderDeviceId: number; ciphertext: string; messageType: 'ciphertext' | 'prekey_bundle' | 'sender_key' | 'server_delivery_receipt' | 'unidentified_sender'; deliveryClass: 'user-visible' | 'background-sync' | 'ephemeral'; timestamp: number; clientMessageId: string; recipientRegistrationId?: number | undefined; contentHint?: number | undefined; serverTimestamp?: number | undefined };

export interface Repository {
  createUser(input: { username: string; normalized: string; displayName: string; passwordHash: string }): Promise<PublicUser>;
  findUserByNormalized(normalized: string): Promise<StoredUser | null>;
  createSession(userId: string, tokenHash: string, expiresAt: Date): Promise<void>;
  findUserBySession(tokenHash: string): Promise<PublicUser | null>;
  revokeSession(tokenHash: string): Promise<void>;
  searchUsers(query: string, excludeUserId: string, limit: number): Promise<PublicUser[]>;
  updateAvatar(userId: string, mime: string, data: Buffer): Promise<PublicUser | null>;
  getAvatar(userId: string): Promise<{ mime: string; data: Buffer } | null>;
  createDirectConversation(userId: string, peerId: string): Promise<Conversation | null>;
  listConversations(userId: string): Promise<Conversation[]>;
  isConversationMember(conversationId: string, userId: string): Promise<boolean>;
  listConversationMemberIds(conversationId: string): Promise<string[]>;
  listEncryptedMessages(conversationId: string, before: string | null, limit: number): Promise<EncryptedMessage[]>;
  createEncryptedMessage(userId: string, input: NewEnvelope): Promise<EncryptedMessage | null>;
  canAccessPeer(userId: string, peerId: string): Promise<boolean>;
  registerProtocolDevice(userId: string, deviceId: number | undefined, encryptedDeviceName: string | undefined): Promise<number>;
  listProtocolDevices(userId: string): Promise<ProtocolDevice[]>;
  provisionPublicIdentity(userId: string, deviceId: number, registrationId: number, identityType: IdentityType, identity: PublicIdentity): Promise<'created' | 'matched' | 'conflict'>;
  getPublicIdentity(userId: string, identityType: IdentityType): Promise<PublicIdentity | null>;
  uploadPreKeys(userId: string, deviceId: number, identityType: IdentityType, keys: PreKeyUpload[]): Promise<boolean>;
  getPreKeyInventory(userId: string, deviceId: number, identityType: IdentityType): Promise<{ ecSignedPreKey: unknown; kemLastResortPreKey: unknown; ecOneTimePreKeyCount: number; kemOneTimePreKeyCount: number } | null>;
  fetchPreKeyBundle(requesterId: string, userId: string, deviceId: number, identityType: IdentityType): Promise<Record<string, unknown> | null>;
  createRelayEnvelope(userId: string, envelope: RelayEnvelope): Promise<RelayEnvelope | null>;
  listPendingEnvelopes(userId: string, deviceId: number): Promise<RelayEnvelope[]>;
  markEnvelopeDelivered(userId: string, envelopeId: string): Promise<boolean>;
}

const publicUserColumns = `u.id, u.username, u.display_name AS "displayName", u.created_at AS "createdAt", u.avatar_updated_at AS "avatarUpdatedAt"`;
const messageColumns = `m.id, m.conversation_id AS "conversationId", m.sender_device_id AS "senderDeviceId", m.recipient_device_id AS "recipientDeviceId", m.protocol_version AS "protocolVersion", encode(m.envelope, 'base64') AS envelope, m.client_message_id AS "clientMessageId", m.created_at AS "createdAt"`;

export class PostgresRepository implements Repository {
  constructor(private readonly pool: pg.Pool) {}
  async createUser(input: { username: string; normalized: string; displayName: string; passwordHash: string }) {
    const client = await this.pool.connect();
    try { await client.query('BEGIN'); const result = await client.query(`INSERT INTO users(username, username_normalized, display_name, password_hash) VALUES($1,$2,$3,$4) RETURNING id, username, display_name AS "displayName", created_at AS "createdAt"`, [input.username, input.normalized, input.displayName, input.passwordHash]); await client.query(`INSERT INTO devices(user_id, label) VALUES($1, 'Navegador principal')`, [result.rows[0].id]); await client.query('COMMIT'); return result.rows[0] as PublicUser; }
    catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  async findUserByNormalized(normalized: string) { const result = await this.pool.query(`SELECT ${publicUserColumns}, u.password_hash AS "passwordHash" FROM users u WHERE u.username_normalized=$1`, [normalized]); return (result.rows[0] as StoredUser | undefined) ?? null; }
  async createSession(userId: string, tokenHash: string, expiresAt: Date) { await this.pool.query('INSERT INTO sessions(user_id, token_hash, expires_at) VALUES($1,$2,$3)', [userId, tokenHash, expiresAt]); }
  async findUserBySession(tokenHash: string) { const result = await this.pool.query(`WITH active AS (UPDATE sessions SET last_seen_at=now() WHERE token_hash=$1 AND revoked_at IS NULL AND expires_at>now() AND last_seen_at>now()-interval '30 minutes' RETURNING user_id) SELECT ${publicUserColumns} FROM active s JOIN users u ON u.id=s.user_id`, [tokenHash]); return (result.rows[0] as PublicUser | undefined) ?? null; }
  async revokeSession(tokenHash: string) { await this.pool.query('UPDATE sessions SET revoked_at=now() WHERE token_hash=$1 AND revoked_at IS NULL', [tokenHash]); }
  async searchUsers(query: string, excludeUserId: string, limit: number) { const result = await this.pool.query(`SELECT ${publicUserColumns} FROM users u WHERE u.id<>$1 AND (u.username_normalized LIKE $2 OR lower(u.display_name) LIKE $2) ORDER BY CASE WHEN u.username_normalized=$3 THEN 0 ELSE 1 END, u.username_normalized LIMIT $4`, [excludeUserId, `${query}%`, query, limit]); return result.rows as PublicUser[]; }
  async updateAvatar(userId: string, mime: string, data: Buffer) { const result = await this.pool.query(`UPDATE users u SET avatar_data=$2,avatar_mime=$3,avatar_updated_at=now() WHERE id=$1 RETURNING ${publicUserColumns}`, [userId, data, mime]); return (result.rows[0] as PublicUser | undefined) ?? null; }
  async getAvatar(userId: string) { const result = await this.pool.query('SELECT avatar_mime AS mime,avatar_data AS data FROM users WHERE id=$1 AND avatar_data IS NOT NULL', [userId]); return (result.rows[0] as { mime: string; data: Buffer } | undefined) ?? null; }
  async createDirectConversation(userId: string, peerId: string) {
    if (userId === peerId) return null; const key = [userId, peerId].sort().join(':'); const client = await this.pool.connect();
    try { await client.query('BEGIN'); const peer = await client.query(`SELECT ${publicUserColumns} FROM users u WHERE u.id=$1`, [peerId]); if (!peer.rows[0]) { await client.query('ROLLBACK'); return null; } const conversation = await client.query(`INSERT INTO conversations(direct_key, created_by) VALUES($1,$2) ON CONFLICT(direct_key) DO UPDATE SET direct_key=EXCLUDED.direct_key RETURNING id, created_at AS "createdAt"`, [key, userId]); await client.query(`INSERT INTO conversation_members(conversation_id,user_id) VALUES($1,$2),($1,$3) ON CONFLICT DO NOTHING`, [conversation.rows[0].id, userId, peerId]); await client.query('COMMIT'); return { ...conversation.rows[0], peer: peer.rows[0] } as Conversation; }
    catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  async listConversations(userId: string) { const result = await this.pool.query(`SELECT c.id, c.created_at AS "createdAt", p.id AS "peerId", p.username AS "peerUsername", p.display_name AS "peerDisplayName", p.created_at AS "peerCreatedAt" FROM conversations c JOIN conversation_members mine ON mine.conversation_id=c.id AND mine.user_id=$1 JOIN conversation_members other ON other.conversation_id=c.id AND other.user_id<>$1 JOIN users p ON p.id=other.user_id ORDER BY c.created_at DESC`, [userId]); return result.rows.map(row => ({ id: row.id, createdAt: row.createdAt, peer: { id: row.peerId, username: row.peerUsername, displayName: row.peerDisplayName, createdAt: row.peerCreatedAt } })) as Conversation[]; }
  async isConversationMember(conversationId: string, userId: string) { const result = await this.pool.query('SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$2', [conversationId, userId]); return result.rowCount === 1; }
  async listConversationMemberIds(conversationId: string) { const result = await this.pool.query('SELECT user_id FROM conversation_members WHERE conversation_id=$1', [conversationId]); return result.rows.map(row => row.user_id as string); }
  async listEncryptedMessages(conversationId: string, before: string | null, limit: number) { const result = await this.pool.query(`SELECT ${messageColumns} FROM encrypted_messages m WHERE m.conversation_id=$1 AND ($2::timestamptz IS NULL OR m.created_at<$2) ORDER BY m.created_at DESC, m.id DESC LIMIT $3`, [conversationId, before, limit]); return (result.rows as EncryptedMessage[]).reverse(); }
  async createEncryptedMessage(userId: string, input: NewEnvelope) { const result = await this.pool.query(`INSERT INTO encrypted_messages(conversation_id,sender_device_id,recipient_device_id,protocol_version,envelope,client_message_id) SELECT $1,$2,$3,$4,decode($5,'base64'),$6 WHERE EXISTS (SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$7) AND EXISTS (SELECT 1 FROM devices WHERE id=$2 AND user_id=$7 AND revoked_at IS NULL) AND EXISTS (SELECT 1 FROM devices d JOIN conversation_members cm ON cm.user_id=d.user_id AND cm.conversation_id=$1 WHERE d.id=$3 AND d.revoked_at IS NULL) ON CONFLICT(sender_device_id,recipient_device_id,client_message_id) DO UPDATE SET client_message_id=EXCLUDED.client_message_id RETURNING id, conversation_id AS "conversationId", sender_device_id AS "senderDeviceId", recipient_device_id AS "recipientDeviceId", protocol_version AS "protocolVersion", encode(envelope,'base64') AS envelope, client_message_id AS "clientMessageId", created_at AS "createdAt"`, [input.conversationId, input.senderDeviceId, input.recipientDeviceId, input.protocolVersion, input.envelope, input.clientMessageId, userId]); return (result.rows[0] as EncryptedMessage | undefined) ?? null; }
  async canAccessPeer(userId: string, peerId: string) { if (userId === peerId) return true; const result = await this.pool.query('SELECT 1 FROM conversation_members mine JOIN conversation_members peer ON peer.conversation_id=mine.conversation_id WHERE mine.user_id=$1 AND peer.user_id=$2 LIMIT 1', [userId, peerId]); return result.rowCount === 1; }
  async registerProtocolDevice(userId: string, requested: number | undefined, encryptedName: string | undefined) {
    const client = await this.pool.connect(); try { await client.query('BEGIN');
      const existing = await client.query('SELECT protocol_device_id FROM devices WHERE user_id=$1 AND protocol_device_id=$2 AND revoked_at IS NULL', [userId, requested ?? 1]);
      if (existing.rows[0]) { await client.query('COMMIT'); return existing.rows[0].protocol_device_id as number; }
      const next = requested ?? Number((await client.query('SELECT COALESCE(max(protocol_device_id),0)+1 AS id FROM devices WHERE user_id=$1', [userId])).rows[0].id);
      if (next < 1 || next > 5) throw new Error('device_limit');
      const unused = await client.query('SELECT id FROM devices WHERE user_id=$1 AND protocol_device_id IS NULL AND revoked_at IS NULL ORDER BY created_at LIMIT 1 FOR UPDATE', [userId]);
      if (unused.rows[0]) await client.query('UPDATE devices SET protocol_device_id=$2, encrypted_device_name=decode($3,\'base64\'), device_type=\'web\' WHERE id=$1', [unused.rows[0].id, next, encryptedName ?? null]);
      else await client.query('INSERT INTO devices(user_id,label,protocol_device_id,encrypted_device_name,device_type) VALUES($1,\'Navegador\',$2,decode($3,\'base64\'),\'web\')', [userId, next, encryptedName ?? null]);
      await client.query('COMMIT'); return next;
    } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  async listProtocolDevices(userId: string) { const result = await this.pool.query(`SELECT protocol_device_id AS "deviceId", CASE WHEN encrypted_device_name IS NULL THEN NULL ELSE encode(encrypted_device_name,'base64') END AS "encryptedDeviceName", device_type AS "deviceType", registration_id IS NOT NULL AS registered, protocol_device_id<>1 AS linked, enabled, extract(epoch from created_at)*1000 AS "createdAt" FROM devices WHERE user_id=$1 AND protocol_device_id IS NOT NULL AND revoked_at IS NULL ORDER BY protocol_device_id`, [userId]); return result.rows as ProtocolDevice[]; }
  async provisionPublicIdentity(userId: string, deviceId: number, registrationId: number, identityType: IdentityType, identity: PublicIdentity) {
    const client = await this.pool.connect(); try { await client.query('BEGIN'); const device = await client.query('SELECT id FROM devices WHERE user_id=$1 AND protocol_device_id=$2 AND revoked_at IS NULL FOR UPDATE', [userId, deviceId]); if (!device.rows[0]) { await client.query('ROLLBACK'); return 'conflict' as const; }
      const current = await client.query('SELECT version,x25519_public_key,ed25519_public_key FROM account_public_identities WHERE user_id=$1 AND identity_type=$2 FOR UPDATE', [userId, identityType]);
      if (current.rows[0] && (current.rows[0].version !== identity.version || current.rows[0].x25519_public_key !== identity.x25519PublicKey || current.rows[0].ed25519_public_key !== identity.ed25519PublicKey)) { await client.query('ROLLBACK'); return 'conflict' as const; }
      if (!current.rows[0]) await client.query('INSERT INTO account_public_identities(user_id,identity_type,version,x25519_public_key,ed25519_public_key) VALUES($1,$2,$3,$4,$5)', [userId, identityType, identity.version, identity.x25519PublicKey, identity.ed25519PublicKey]);
      await client.query('UPDATE devices SET registration_id=$3 WHERE user_id=$1 AND protocol_device_id=$2', [userId, deviceId, registrationId]); await client.query('COMMIT'); return current.rows[0] ? 'matched' as const : 'created' as const;
    } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  async getPublicIdentity(userId: string, identityType: IdentityType) { const result = await this.pool.query('SELECT version,x25519_public_key AS "x25519PublicKey",ed25519_public_key AS "ed25519PublicKey" FROM account_public_identities WHERE user_id=$1 AND identity_type=$2', [userId, identityType]); return (result.rows[0] as PublicIdentity | undefined) ?? null; }
  async uploadPreKeys(userId: string, deviceId: number, identityType: IdentityType, keys: PreKeyUpload[]) { const client = await this.pool.connect(); try { await client.query('BEGIN'); const device = await client.query('SELECT id FROM devices WHERE user_id=$1 AND protocol_device_id=$2 AND registration_id IS NOT NULL AND revoked_at IS NULL', [userId, deviceId]); if (!device.rows[0]) { await client.query('ROLLBACK'); return false; } for (const key of keys) await client.query(`INSERT INTO protocol_prekeys(device_id,identity_type,key_type,key_id,public_key,signature) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(device_id,identity_type,key_type,key_id) DO UPDATE SET public_key=EXCLUDED.public_key,signature=EXCLUDED.signature,claimed_at=NULL,created_at=now(),expires_at=now()+interval '14 days'`, [device.rows[0].id, identityType, key.type, key.keyId, key.publicKey, key.signature ?? null]); await client.query('COMMIT'); return true; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async getPreKeyInventory(userId: string, deviceId: number, identityType: IdentityType) { const result = await this.pool.query(`SELECT CASE WHEN signed.key_id IS NULL THEN NULL ELSE jsonb_build_object('keyId',signed.key_id,'createdAt',(extract(epoch from signed.created_at)*1000)::bigint,'expiresAt',(extract(epoch from signed.expires_at)*1000)::bigint,'publicKey',signed.public_key) END AS "ecSignedPreKey", CASE WHEN kem.key_id IS NULL THEN NULL ELSE jsonb_build_object('keyId',kem.key_id,'createdAt',(extract(epoch from kem.created_at)*1000)::bigint,'expiresAt',(extract(epoch from kem.expires_at)*1000)::bigint,'publicKey',kem.public_key) END AS "kemLastResortPreKey", (SELECT count(*)::int FROM protocol_prekeys p WHERE p.device_id=d.id AND p.identity_type=$3 AND p.key_type='ecPreKey' AND p.claimed_at IS NULL) AS "ecOneTimePreKeyCount", (SELECT count(*)::int FROM protocol_prekeys p WHERE p.device_id=d.id AND p.identity_type=$3 AND p.key_type='kemOneTimePreKey' AND p.claimed_at IS NULL) AS "kemOneTimePreKeyCount" FROM devices d LEFT JOIN LATERAL (SELECT key_id,created_at,expires_at,public_key FROM protocol_prekeys WHERE device_id=d.id AND identity_type=$3 AND key_type='ecSignedPreKey' AND claimed_at IS NULL ORDER BY created_at DESC LIMIT 1) signed ON true LEFT JOIN LATERAL (SELECT key_id,created_at,expires_at,public_key FROM protocol_prekeys WHERE device_id=d.id AND identity_type=$3 AND key_type='kemLastResortPreKey' AND claimed_at IS NULL ORDER BY created_at DESC LIMIT 1) kem ON true WHERE d.user_id=$1 AND d.protocol_device_id=$2 AND d.revoked_at IS NULL`, [userId, deviceId, identityType]); return result.rows[0] ?? null; }
  async fetchPreKeyBundle(requesterId: string, userId: string, deviceId: number, identityType: IdentityType) {
    const client = await this.pool.connect(); try { await client.query('BEGIN'); const allowed = await client.query('SELECT 1 FROM conversations c JOIN conversation_members a ON a.conversation_id=c.id AND a.user_id=$1 JOIN conversation_members b ON b.conversation_id=c.id AND b.user_id=$2', [requesterId, userId]); if (!allowed.rows[0] && requesterId !== userId) { await client.query('ROLLBACK'); return null; }
      const base = await client.query(`SELECT d.id,d.registration_id,i.version,i.x25519_public_key,i.ed25519_public_key FROM devices d JOIN account_public_identities i ON i.user_id=d.user_id AND i.identity_type=$3 WHERE d.user_id=$1 AND d.protocol_device_id=$2 AND d.enabled AND d.revoked_at IS NULL FOR UPDATE`, [userId, deviceId, identityType]); if (!base.rows[0]?.registration_id) { await client.query('ROLLBACK'); return null; }
      const pick = async (type: string, consume: boolean) => { const r = await client.query(`SELECT key_id,public_key,signature FROM protocol_prekeys WHERE device_id=$1 AND identity_type=$2 AND key_type=$3 AND claimed_at IS NULL ORDER BY key_id LIMIT 1 FOR UPDATE SKIP LOCKED`, [base.rows[0].id, identityType, type]); if (r.rows[0] && consume) await client.query('UPDATE protocol_prekeys SET claimed_at=now() WHERE device_id=$1 AND identity_type=$2 AND key_type=$3 AND key_id=$4', [base.rows[0].id, identityType, type, r.rows[0].key_id]); return r.rows[0]; };
      const [signed, ec, kemOne, kemLast] = await Promise.all([pick('ecSignedPreKey', false), pick('ecPreKey', true), pick('kemOneTimePreKey', true), pick('kemLastResortPreKey', false)]); if (!signed) { await client.query('ROLLBACK'); return null; }
      const mapped = (k: any) => k ? { keyId: k.key_id, publicKey: k.public_key, ...(k.signature ? { signature: k.signature } : {}) } : null;
      await client.query('COMMIT'); return { registrationId: base.rows[0].registration_id, deviceId, identity: { version: base.rows[0].version, x25519PublicKey: base.rows[0].x25519_public_key, ed25519PublicKey: base.rows[0].ed25519_public_key }, ecSignedPreKey: mapped(signed), ecOneTimePreKey: mapped(ec), ...(kemOne ? { kemOneTimePreKey: mapped(kemOne) } : { kemLastResortPreKey: mapped(kemLast) }) };
    } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  async createRelayEnvelope(userId: string, envelope: RelayEnvelope) { const result = await this.pool.query(`INSERT INTO e2ee_envelopes(conversation_id,target_user_id,target_device_id,sender_user_id,sender_device_id,ciphertext,message_type,delivery_class,client_timestamp,client_message_id,recipient_registration_id,content_hint,server_timestamp) SELECT c.id,$2,$3,$1,$4,decode($5,'base64'),$6,$7,$8,$9,$10,$11,(extract(epoch from clock_timestamp())*1000)::bigint FROM conversations c JOIN conversation_members a ON a.conversation_id=c.id AND a.user_id=$1 JOIN conversation_members b ON b.conversation_id=c.id AND b.user_id=$2 JOIN devices sd ON sd.user_id=$1 AND sd.protocol_device_id=$4 AND sd.revoked_at IS NULL JOIN devices rd ON rd.user_id=$2 AND rd.protocol_device_id=$3 AND rd.revoked_at IS NULL WHERE ($10::integer IS NULL OR rd.registration_id=$10) ON CONFLICT(sender_user_id,client_message_id,target_device_id) DO UPDATE SET client_message_id=EXCLUDED.client_message_id RETURNING id,target_user_id AS "targetUserId",target_device_id AS "targetDeviceId",sender_user_id AS "senderUserId",sender_device_id AS "senderDeviceId",encode(ciphertext,'base64') AS ciphertext,message_type AS "messageType",delivery_class AS "deliveryClass",client_timestamp::float8 AS timestamp,client_message_id AS "clientMessageId",recipient_registration_id AS "recipientRegistrationId",content_hint AS "contentHint",server_timestamp::float8 AS "serverTimestamp"`, [userId, envelope.targetUserId, envelope.targetDeviceId, envelope.senderDeviceId, envelope.ciphertext, envelope.messageType, envelope.deliveryClass, envelope.timestamp, envelope.clientMessageId, envelope.recipientRegistrationId ?? null, envelope.contentHint ?? null]); return (result.rows[0] as RelayEnvelope | undefined) ?? null; }
  async listPendingEnvelopes(userId: string, deviceId: number) { const result = await this.pool.query(`SELECT id,target_user_id AS "targetUserId",target_device_id AS "targetDeviceId",sender_user_id AS "senderUserId",sender_device_id AS "senderDeviceId",encode(ciphertext,'base64') AS ciphertext,message_type AS "messageType",delivery_class AS "deliveryClass",client_timestamp::float8 AS timestamp,client_message_id AS "clientMessageId",recipient_registration_id AS "recipientRegistrationId",content_hint AS "contentHint",server_timestamp::float8 AS "serverTimestamp" FROM e2ee_envelopes WHERE target_user_id=$1 AND target_device_id=$2 AND delivered_at IS NULL ORDER BY created_at,id LIMIT 500`, [userId, deviceId]); return result.rows as RelayEnvelope[]; }
  async markEnvelopeDelivered(userId: string, envelopeId: string) { const result = await this.pool.query('UPDATE e2ee_envelopes SET delivered_at=COALESCE(delivered_at,now()) WHERE id=$1 AND target_user_id=$2', [envelopeId, userId]); return result.rowCount === 1; }
}
